# Install PowerShell Aliases for YoutubeRag.NET
# DEVOPS-012: Installer for PowerShell aliases
#
# This script installs the ps-aliases.ps1 to your PowerShell profile
# so they're available in every PowerShell session.
#
# Usage:
#   .\scripts\install-aliases.ps1

param(
    [switch]$Uninstall
)

$ErrorActionPreference = "Stop"

# Helper function for colored output
function Write-ColorOutput($Message, $Color = "White") {
    Write-Host $Message -ForegroundColor $Color
}

# Get the path to ps-aliases.ps1
$aliasesPath = Join-Path $PSScriptRoot "ps-aliases.ps1"
$aliasesPath = Resolve-Path $aliasesPath

# Check if ps-aliases.ps1 exists
if (-not (Test-Path $aliasesPath)) {
    Write-ColorOutput "❌ Error: ps-aliases.ps1 not found at $aliasesPath" "Red"
    exit 1
}

# Get PowerShell profile path
$profilePath = $PROFILE.CurrentUserAllHosts

Write-ColorOutput "PowerShell Aliases Installer" "Cyan"
Write-ColorOutput "============================" "Cyan"
Write-Host ""
Write-Host "Aliases file:   $aliasesPath"
Write-Host "Profile:        $profilePath"
Write-Host ""

if ($Uninstall) {
    # Uninstall aliases
    Write-ColorOutput "Uninstalling YoutubeRag.NET aliases..." "Yellow"

    if (-not (Test-Path $profilePath)) {
        Write-ColorOutput "✅ Profile doesn't exist, nothing to uninstall" "Green"
        exit 0
    }

    # Read profile content
    $profileContent = Get-Content $profilePath -Raw

    # Remove the alias loading line
    $marker = "# YoutubeRag.NET Aliases"
    if ($profileContent -match $marker) {
        $lines = Get-Content $profilePath
        $newLines = $lines | Where-Object { $_ -notmatch "YoutubeRag\.NET Aliases" -and $_ -notmatch "ps-aliases\.ps1" }

        # Write back to profile
        $newLines | Set-Content $profilePath -Force

        Write-ColorOutput "✅ Aliases uninstalled from PowerShell profile" "Green"
        Write-Host ""
        Write-Host "Restart PowerShell for changes to take effect"
    } else {
        Write-ColorOutput "⚠️  Aliases not found in profile" "Yellow"
    }

    exit 0
}

# Install aliases
Write-ColorOutput "Installing YoutubeRag.NET aliases..." "Cyan"

# Create profile if it doesn't exist
if (-not (Test-Path $profilePath)) {
    Write-ColorOutput "Creating PowerShell profile..." "Yellow"
    $profileDir = Split-Path $profilePath -Parent
    if (-not (Test-Path $profileDir)) {
        New-Item -ItemType Directory -Path $profileDir -Force | Out-Null
    }
    New-Item -ItemType File -Path $profilePath -Force | Out-Null
    Write-ColorOutput "✅ Profile created at $profilePath" "Green"
}

# Check if aliases are already in profile
$profileContent = Get-Content $profilePath -Raw -ErrorAction SilentlyContinue
$marker = "# YoutubeRag.NET Aliases"

if ($profileContent -match [regex]::Escape($marker)) {
    Write-ColorOutput "⚠️  Aliases already installed in profile" "Yellow"
    $response = Read-Host "Do you want to update the path? [y/N]"
    if ($response -ne 'y' -and $response -ne 'Y') {
        Write-ColorOutput "❌ Installation cancelled" "Red"
        exit 0
    }

    # Remove existing alias loading
    $lines = Get-Content $profilePath
    $newLines = $lines | Where-Object { $_ -notmatch "YoutubeRag\.NET Aliases" -and $_ -notmatch "ps-aliases\.ps1" }
    $newLines | Set-Content $profilePath -Force
    Write-ColorOutput "✅ Removed existing alias configuration" "Green"
}

# Add alias loading to profile
$aliasLoadCommand = @"

# YoutubeRag.NET Aliases - Auto-generated by install-aliases.ps1
if (Test-Path "$aliasesPath") {
    . "$aliasesPath"
} else {
    Write-Warning "YoutubeRag.NET aliases not found at $aliasesPath"
}
"@

Add-Content -Path $profilePath -Value $aliasLoadCommand

Write-ColorOutput "✅ Aliases installed successfully!" "Green"
Write-Host ""
Write-Host "Installation complete. The aliases will be available in new PowerShell sessions."
Write-Host ""
Write-Host "To use the aliases immediately in this session, run:"
Write-ColorOutput "  . $aliasesPath" "Yellow"
Write-Host ""
Write-Host "Or restart PowerShell."
Write-Host ""
Write-Host "Available commands:"
Write-Host "  - dev, test, build, migrate, clean, etc."
Write-Host "  - Type 'help' after loading aliases to see all commands"
Write-Host ""
Write-ColorOutput "🎉 Setup complete!" "Green"

# Ask if user wants to load aliases now
$loadNow = Read-Host "Load aliases in this session now? [Y/n]"
if ($loadNow -ne 'n' -and $loadNow -ne 'N') {
    . $aliasesPath
    Write-Host ""
    Write-ColorOutput "✅ Aliases loaded! Type 'help' to see available commands" "Green"
}
